import type { Config, Data } from "@measured/puck";
import { cn } from "@/lib/utils";

export type VisualEditorData = Data;
const alignOptions = [{ label: "Left", value: "left" }, { label: "Center", value: "center" }, { label: "Right", value: "right" }] as const;
const toneOptions = [{ label: "Default", value: "default" }, { label: "Crimson", value: "crimson" }, { label: "Slate", value: "slate" }, { label: "Gold", value: "gold" }] as const;
function toneClass(tone?: string) { return tone === "crimson" ? "border-primary/40 bg-primary/10" : tone === "slate" ? "border-slate-500/30 bg-slate-500/10" : tone === "gold" ? "border-amber-500/30 bg-amber-500/10" : "border-border bg-card"; }
function safeHref(href?: string) { const value = String(href || "#"); return value.startsWith("/") || value.startsWith("https://") || value.startsWith("mailto:") || value.startsWith("tel:") || value === "#" ? value : "#"; }

export const defaultVisualEditorData: VisualEditorData = { root: { props: {} }, content: [{ type: "HeroSection", props: { eyebrow: "MyOrder.fun", title: "Editable marketing page", body: "Compose safe content and catalog presentation with approved blocks.", ctaLabel: "Order now", ctaHref: "/catalog", tone: "crimson", align: "left" } }] };

export const visualEditorConfig: Config = {
  categories: { content: { title: "Approved components", defaultExpanded: true, components: ["HeroSection", "TextBlock", "ImageBlock", "CTAButton", "ProductPromoGrid", "FAQBlock", "FeatureGrid", "AnnouncementBanner", "ContactInfoBlock", "StoreHoursBlock", "CatalogPresentationBlock"] } },
  components: {
    HeroSection: { label: "Hero section", fields: { eyebrow: { type: "text" }, title: { type: "text" }, body: { type: "textarea" }, ctaLabel: { type: "text" }, ctaHref: { type: "text" }, align: { type: "radio", options: [...alignOptions] }, tone: { type: "select", options: [...toneOptions] } }, defaultProps: { eyebrow: "Featured", title: "Hero title", body: "Safe editable copy.", ctaLabel: "Learn more", ctaHref: "/catalog", align: "left", tone: "default" }, render: ({ eyebrow, title, body, ctaLabel, ctaHref, align, tone }) => <section className={cn("rounded-2xl border p-8", toneClass(tone), align === "center" && "text-center", align === "right" && "text-right")}><p className="text-xs font-bold uppercase tracking-widest text-primary">{eyebrow}</p><h1 className="mt-3 text-4xl font-black">{title}</h1><p className="mt-4 whitespace-pre-line text-muted-foreground">{body}</p>{ctaLabel ? <a className="mt-6 inline-flex rounded-full bg-primary px-5 py-2 font-semibold text-primary-foreground" href={safeHref(ctaHref)}>{ctaLabel}</a> : null}</section> },
    TextBlock: { label: "Text block", fields: { text: { type: "textarea" }, align: { type: "radio", options: [...alignOptions] } }, defaultProps: { text: "Editable text", align: "left" }, render: ({ text, align }) => <p className={cn("whitespace-pre-line leading-7 text-muted-foreground", align === "center" && "text-center", align === "right" && "text-right")}>{text}</p> },
    ImageBlock: { label: "Image", fields: { imageUrl: { type: "text" }, alt: { type: "text" }, caption: { type: "text" } }, defaultProps: { imageUrl: "", alt: "", caption: "" }, render: ({ imageUrl, alt, caption }) => <figure>{imageUrl ? <img className="max-h-96 w-full rounded-xl object-cover" src={safeHref(imageUrl)} alt={String(alt || "")} /> : <div className="rounded-xl border p-10 text-center text-muted-foreground">Add an HTTPS image URL</div>}{caption ? <figcaption className="mt-2 text-center text-sm text-muted-foreground">{caption}</figcaption> : null}</figure> },
    CTAButton: { label: "CTA button", fields: { label: { type: "text" }, href: { type: "text" }, variant: { type: "radio", options: [{ label: "Primary", value: "primary" }, { label: "Secondary", value: "secondary" }] } }, defaultProps: { label: "Button", href: "/catalog", variant: "primary" }, render: ({ label, href, variant }) => <a className={cn("inline-flex rounded-md px-4 py-2 font-semibold", variant === "secondary" ? "border" : "bg-primary text-primary-foreground")} href={safeHref(href)}>{label}</a> },
    ProductPromoGrid: { label: "Product promo grid", fields: { title: { type: "text" }, products: { type: "textarea" }, layout: { type: "radio", options: [{ label: "2 columns", value: "2" }, { label: "3 columns", value: "3" }] } }, defaultProps: { title: "Featured products", products: "Popular item — New\nLimited item — Limited", layout: "2" }, render: ({ title, products, layout }) => <section><h2 className="text-2xl font-bold">{title}</h2><div className={cn("mt-4 grid gap-3", layout === "3" ? "md:grid-cols-3" : "md:grid-cols-2")}>{String(products ?? "").split("\n").filter(Boolean).slice(0, 12).map((product) => <div key={product} className="rounded-lg border p-4">{product}</div>)}</div></section> },
    FAQBlock: { label: "FAQ", fields: { title: { type: "text" }, questions: { type: "textarea" } }, defaultProps: { title: "Questions", questions: "Question?\nAnswer." }, render: ({ title, questions }) => <section><h2 className="text-2xl font-bold">{title}</h2><div className="mt-3 whitespace-pre-line rounded-xl border p-4 text-muted-foreground">{questions}</div></section> },
    FeatureGrid: { label: "Feature grid", fields: { title: { type: "text" }, features: { type: "textarea" } }, defaultProps: { title: "Features", features: "Fast checkout\nLocal pickup\nFresh inventory labels" }, render: ({ title, features }) => <section><h2 className="text-2xl font-bold">{title}</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{String(features ?? "").split("\n").filter(Boolean).slice(0, 9).map((feature) => <div key={feature} className="rounded-lg border p-4">{feature}</div>)}</div></section> },
    AnnouncementBanner: { label: "Announcement", fields: { text: { type: "text" }, tone: { type: "select", options: [...toneOptions] } }, defaultProps: { text: "Announcement", tone: "gold" }, render: ({ text, tone }) => <div className={cn("rounded-xl border p-4 font-semibold", toneClass(tone))}>{text}</div> },
    ContactInfoBlock: { label: "Contact info", fields: { title: { type: "text" }, phone: { type: "text" }, email: { type: "text" }, address: { type: "textarea" } }, defaultProps: { title: "Contact us", phone: "", email: "", address: "" }, render: ({ title, phone, email, address }) => <section className="rounded-xl border p-5"><h2 className="text-xl font-bold">{title}</h2><p>{phone}</p><p>{email}</p><p className="whitespace-pre-line text-muted-foreground">{address}</p></section> },

    CatalogPresentationBlock: { label: "Catalog presentation", fields: { title: { type: "text" }, displayName: { type: "text" }, description: { type: "textarea" }, imageUrl: { type: "text" }, categoryDisplay: { type: "text" }, badges: { type: "textarea" }, featured: { type: "radio", options: [{ label: "Featured", value: "yes" }, { label: "Standard", value: "no" }] }, sortOrder: { type: "text" }, quantityLabel: { type: "text" }, priceDisplayFormat: { type: "text" }, availabilityText: { type: "text" }, layoutStyle: { type: "radio", options: [{ label: "Card", value: "card" }, { label: "Compact", value: "compact" }] }, visible: { type: "radio", options: [{ label: "Visible", value: "yes" }, { label: "Hidden", value: "no" }] } }, defaultProps: { title: "Catalog presentation", displayName: "Product display name", description: "Customer-facing description only. Inventory and pricing logic stay in secured product/inventory APIs.", imageUrl: "", categoryDisplay: "Featured", badges: "New\nPopular", featured: "yes", sortOrder: "10", quantityLabel: "Available today", priceDisplayFormat: "Show standard menu price", availabilityText: "Ready for pickup", layoutStyle: "card", visible: "yes" }, render: ({ title, displayName, description, imageUrl, categoryDisplay, badges, featured, sortOrder, quantityLabel, priceDisplayFormat, availabilityText, layoutStyle, visible }) => <section className={cn("rounded-xl border p-5", visible === "no" && "opacity-60", layoutStyle === "compact" && "p-3")}><div className="flex gap-4"><div className="h-24 w-24 shrink-0 overflow-hidden rounded-lg border bg-muted">{imageUrl ? <img src={safeHref(imageUrl)} alt={String(displayName || title || "Catalog item")} className="h-full w-full object-cover" /> : null}</div><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-widest text-muted-foreground">{title} · {categoryDisplay} · sort {sortOrder}</p><h3 className="text-xl font-bold">{displayName}</h3><p className="mt-1 whitespace-pre-line text-sm text-muted-foreground">{description}</p><div className="mt-3 flex flex-wrap gap-2">{featured === "yes" ? <span className="rounded-full bg-primary px-2 py-1 text-xs text-primary-foreground">Featured</span> : null}{String(badges ?? "").split("\n").filter(Boolean).slice(0, 5).map((badge) => <span key={badge} className="rounded-full border px-2 py-1 text-xs">{badge}</span>)}</div><p className="mt-2 text-xs text-muted-foreground">{quantityLabel} · {priceDisplayFormat} · {availabilityText}</p></div></div></section> },
    StoreHoursBlock: { label: "Store hours", fields: { title: { type: "text" }, hours: { type: "textarea" } }, defaultProps: { title: "Hours", hours: "Mon–Fri 9–5" }, render: ({ title, hours }) => <section className="rounded-xl border p-5"><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 whitespace-pre-line text-muted-foreground">{hours}</p></section> },
  },
};
