import { Router, type IRouter } from "express";
import webhooksRouter from "./webhooks";
import usersRouter from "./users";
import onboardingRouter from "./onboarding";
import tenantsRouter from "./tenants";
import catalogRouter from "./catalog";
import ordersRouter from "./orders";
import auditRouter from "./audit";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import aiRouter from "./ai";
import paymentsRouter from "./payments";
import shiftsRouter from "./shifts";
import printRouter from "./print";
import adminPrintersRouter from "./admin-printers";
import importRouter from "./import";
import settingsRouter from "./settings";
import woocommerceRouter from "./woocommerce";
import inventoryRouter from "./inventory";
import sessionRouter from "./session";
import feedbackRouter from "./feedback";
import integrationsRouter from "./integrations";
import creditsRouter from "./credits";
import reportsRouter from "./reports";
import proposalsRouter from "./proposals";
import communicationsRouter from "./communications";
import visualEditorRouter from "./visual-editor";

const router: IRouter = Router();

router.use(webhooksRouter);
router.use(usersRouter);
router.use(onboardingRouter);
router.use(tenantsRouter);
router.use(catalogRouter);
router.use(ordersRouter);
router.use(notificationsRouter);
router.use(shiftsRouter);
router.use(auditRouter);
router.use(adminRouter);
router.use(aiRouter);
router.use(paymentsRouter);
router.use(printRouter);
router.use(adminPrintersRouter);
router.use(importRouter);
router.use(settingsRouter);
router.use(woocommerceRouter);
router.use(inventoryRouter);
router.use(sessionRouter);
router.use(feedbackRouter);
router.use(integrationsRouter);
router.use(creditsRouter);
router.use(reportsRouter);
router.use(proposalsRouter);
router.use(communicationsRouter);
router.use(visualEditorRouter);

export default router;
