import { Router, type IRouter } from "express";
import webhooksRouter from "./webhooks";
import usersRouter from "./users";
import onboardingRouter from "./onboarding";
import tenantsRouter from "./tenants";
import catalogRouter from "./catalog";
import ordersRouter from "./orders";
import auditRouter from "./audit";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import aiRouter from "./ai";
import paymentsRouter from "./payments";
import paypalPaymentsRouter from "./paypal-payments";
import shiftsRouter from "./shifts";
import shiftQueueRouter from "./shift-queue";
import printRouter from "./print";
import adminPrintersRouter from "./admin-printers";
import importRouter from "./import";
import settingsRouter from "./settings";
import tenantSettingsRouter from "./tenant-settings";
import woocommerceRouter from "./woocommerce";
import inventoryRouter from "./inventory";
import sessionRouter from "./session";
import feedbackRouter from "./feedback";
import integrationsRouter from "./integrations";
import creditsRouter from "./credits";
import reportsRouter from "./reports";
import visualEditorRouter from "./visual-editor";
import rolePermissionsRouter from "./role-permissions";
import privacyRouter from "./privacy";
import pwaPushRouter from "./pwa-push";
import taxConfigurationsRouter from "./tax-configurations";
import stagingStickerBridgeRouter from "./staging-sticker-bridge";
import returnsRouter from "./returns";

const router: IRouter = Router();

router.use(webhooksRouter);
router.use(stagingStickerBridgeRouter);
router.use(usersRouter);
router.use(onboardingRouter);
router.use(tenantsRouter);
router.use(catalogRouter);
router.use(ordersRouter);
router.use(returnsRouter);
router.use(notificationsRouter);
router.use(settingsRouter);
router.use(tenantSettingsRouter);
router.use(shiftsRouter);
router.use(shiftQueueRouter);
router.use(aiRouter);
router.use(paypalPaymentsRouter);
router.use(paymentsRouter);
router.use(printRouter);
router.use(adminPrintersRouter);
router.use(importRouter);
router.use(woocommerceRouter);
router.use(inventoryRouter);
router.use(sessionRouter);
router.use(feedbackRouter);
router.use(integrationsRouter);
router.use(creditsRouter);
router.use(reportsRouter);
router.use(taxConfigurationsRouter);
router.use(visualEditorRouter);
router.use(rolePermissionsRouter);
router.use(privacyRouter);
router.use(pwaPushRouter);
// These legacy routers install router-wide admin role middleware. Keep them
// last so an unrelated route owned by a later module (for example inventory,
// printers, or role permissions) is not rejected before Express can match it.
router.use(auditRouter);
router.use(adminRouter);

export default router;
