import crypto from "node:crypto";
import { Router } from "express";
import { db, contractsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { validateDocumensoConfig } from "../documenso/config";
import { documensoClient } from "../documenso/client";
import { renderContractSigningEmail } from "../emails/signingEmail";
import { canSignContract } from "../permissions/canSignContract";
import { buildSigningUrl } from "../signing/tokens";
import { addSigner, ensureContract, findSignerByDocumensoRecipient, findSignerByToken, listContracts, listSigners, recordDocumensoWebhookEvent, updateSignerStatus, upsertContract, writeContractAudit } from "../services/store";
import { archiveContractDocument, writeDocumentAudit } from "../../document-hub/services/store";
const router = Router();

async function markContractFullySigned(contractId: string): Promise<void> {
  const signers = await listSigners(contractId);
  if (signers.length > 0 && signers.every((s) => !s.isRequired || s.status === "signed")) {
    if (process.env.NODE_ENV === "test") await upsertContract({ id: contractId, status: "fully_signed" });
    else await db.update(contractsTable).set({ status: "fully_signed", updatedAt: new Date() }).where(eq(contractsTable.id, contractId));
    const contract = await ensureContract(contractId);
    await writeContractAudit({ contractId, companyId: contract.companyId, action: "contract_fully_signed", afterJson: { status: "fully_signed" } });
  }
}

router.get("/contractor-hub/contracts", async (_req, res): Promise<void> => { res.json({ contracts: await listContracts() }); });
router.get("/contractor-hub/contracts/:id", async (req, res): Promise<void> => { res.json({ contract: await ensureContract(req.params.id), signers: await listSigners(req.params.id) }); });
router.get("/contractor-hub/contracts/:id/sign", async (req, res): Promise<void> => { const contract = await ensureContract(req.params.id); res.json({ contract, canSign: await canSignContract({ contractId: contract.id, userId: String(req.query.userId ?? ""), email: String(req.query.email ?? ""), signingToken: String(req.query.token ?? ""), companyId: contract.companyId, role: String(req.query.role ?? "") }) }); });
router.post("/contractor-hub/contracts/:id/signers", async (req, res): Promise<void> => { await ensureContract(req.params.id); const result = await addSigner({ contractId: req.params.id, ...req.body }); await writeContractAudit({ contractId: req.params.id, companyId: result.signer.companyId, action: "signer_assigned", afterJson: result.signer }); res.status(201).json({ signer: result.signer, signingUrl: buildSigningUrl(result.token) }); });
router.post("/contractor-hub/contracts/:id/delegate-signer", async (req, res): Promise<void> => { await ensureContract(req.params.id); const result = await addSigner({ contractId: req.params.id, email: req.body.email, name: req.body.name, signerType: req.body.replacesSignerId ? "replacement" : "delegated", isDelegated: true, delegatedByUserId: req.body.delegatedByUserId, replacesSignerId: req.body.replacesSignerId }); await writeContractAudit({ contractId: req.params.id, companyId: result.signer.companyId, action: result.signer.replacesSignerId ? "replacement_signer_delegated" : "additional_signer_delegated", afterJson: result.signer }); res.status(201).json({ signer: result.signer, signingUrl: buildSigningUrl(result.token) }); });
router.post("/contractor-hub/contracts/:id/send-signing-email", async (req, res): Promise<void> => { const contract = await ensureContract(req.params.id); const result = await addSigner({ contractId: req.params.id, email: req.body.email, name: req.body.name, status: "sent" }); const signingUrl = buildSigningUrl(result.token); await writeContractAudit({ contractId: contract.id, companyId: contract.companyId, action: "signing_email_sent", afterJson: { signerId: result.signer.id, email: result.signer.email } }); res.json({ email: renderContractSigningEmail({ contractTitle: contract.title, companyName: req.body.companyName ?? "MyPayLink", signerName: result.signer.name ?? result.signer.email, signingUrl, expiresAt: result.signer.signingTokenExpiresAt }), signingUrl }); });
router.post("/contractor-hub/contracts/:id/documenso/create", async (req, res): Promise<void> => { const valid = validateDocumensoConfig(); if (!valid.ok) { res.status(503).json({ error: valid.error }); return; } const contract = await ensureContract(req.params.id); const created = await documensoClient.createDocument({ title: contract.title, fileName: req.body?.fileName ?? `${contract.id}.pdf`, fileBase64: req.body?.fileBase64 }); await upsertContract({ ...contract, documensoDocumentId: created.id, status: "sent_for_signature" }); const signers = await listSigners(contract.id); if (signers.length > 0) await documensoClient.createRecipients(created.id, signers.map((s) => ({ email: s.email, name: s.name, signingOrder: s.signingOrder }))); await documensoClient.sendDocument(created.id); await writeContractAudit({ contractId: contract.id, companyId: contract.companyId, action: "documenso_sent", afterJson: { documensoDocumentId: created.id } }); res.status(201).json({ documensoDocumentId: created.id, baseUrl: valid.config.baseUrl }); });
router.post("/contractor-hub/contracts/:id/documenso/sync", async (req, res): Promise<void> => { const contract = await ensureContract(req.params.id); const status = contract.documensoDocumentId ? (await documensoClient.getDocument(contract.documensoDocumentId)).status : req.body?.status ?? "completed"; if (status === "completed" || status === "COMPLETED") await markContractFullySigned(contract.id); res.json({ contractId: contract.id, documensoDocumentId: contract.documensoDocumentId, status }); });
router.post("/contractor-hub/contracts/:id/archive-final", async (req, res): Promise<void> => { const contract = await ensureContract(req.params.id); const asset = await archiveContractDocument({ companyId: contract.companyId, contractId: contract.id, title: `${contract.title} - Signed`, fileName: req.body?.fileName ?? `${contract.id}-signed.pdf`, storageKey: req.body?.storageKey, documensoDocumentId: contract.documensoDocumentId ?? undefined, signerEmail: req.body?.signerEmail }); await markContractFullySigned(contract.id); res.status(201).json({ asset }); });
router.post("/contractor-hub/documenso/webhook", async (req, res): Promise<void> => { const eventId = String(req.body.eventId ?? req.body.id ?? crypto.randomUUID()); const contractId = String(req.body.contractId ?? ""); const recipientId = String(req.body.recipientId ?? ""); const status = String(req.body?.status ?? req.body.event ?? "").toLowerCase(); const firstDelivery = await recordDocumensoWebhookEvent({ eventId, contractId: contractId || undefined, eventType: status || "unknown", payload: req.body }); if (!firstDelivery) { res.json({ ok: true, eventId, duplicate: true }); return; } const signer = contractId && recipientId ? await findSignerByDocumensoRecipient(contractId, recipientId) : undefined; if (signer && (status.includes("complete") || status.includes("sign"))) await updateSignerStatus(signer.id, "signed"); if (contractId && (status.includes("complete") || status.includes("sign"))) { const contract = await ensureContract(contractId); let storageKey = `${contract.id}-signed.pdf`; if (contract.documensoDocumentId && validateDocumensoConfig().config.enabled) { const pdf = await documensoClient.downloadCompletedPdf(contract.documensoDocumentId); storageKey = `documenso/${contract.documensoDocumentId}/${pdf.length}-${storageKey}`; } const asset = await archiveContractDocument({ companyId: contract.companyId, contractId: contract.id, title: `${contract.title} - Signed`, fileName: `${contract.id}-signed.pdf`, storageKey, documensoDocumentId: contract.documensoDocumentId ?? undefined, signerEmail: signer?.email }); await writeDocumentAudit({ documentAssetId: asset.id, companyId: contract.companyId, action: "documenso_webhook", afterJson: { eventId, status } }); await writeContractAudit({ contractId: contract.id, companyId: contract.companyId, action: "final_pdf_archived", afterJson: { eventId, assetId: asset.id, storageKey } }); await markContractFullySigned(contract.id); } res.json({ ok: true, eventId, duplicate: false }); });
router.get("/signing/contracts/:token", async (req, res): Promise<void> => { const signer = await findSignerByToken(req.params.token); if (!signer || !signer.signingTokenExpiresAt || signer.signingTokenExpiresAt <= new Date()) { res.status(404).json({ error: "Signing link is invalid or expired" }); return; } const contract = await ensureContract(signer.contractId); await writeContractAudit({ contractId: contract.id, companyId: contract.companyId, action: "signer_viewed", afterJson: { signerId: signer.id } }); res.json({ contract, signer, canSign: true, signingMode: validateDocumensoConfig().config.enabled ? "documenso" : "paylink" }); });
router.post("/signing/contracts/:token/complete", async (req, res): Promise<void> => { const signer = await findSignerByToken(req.params.token); if (!signer || !signer.signingTokenExpiresAt || signer.signingTokenExpiresAt <= new Date()) { res.status(404).json({ error: "Signing link is invalid or expired" }); return; } const signed = await updateSignerStatus(signer.id, "signed"); const contract = await ensureContract(signer.contractId); const asset = await archiveContractDocument({ companyId: contract.companyId, contractId: contract.id, title: `${contract.title} - Signed`, fileName: `${contract.id}-signed.pdf`, documensoDocumentId: contract.documensoDocumentId ?? undefined, signerEmail: signer.email }); await writeContractAudit({ contractId: contract.id, companyId: contract.companyId, action: "signer_completed", afterJson: { signerId: signer.id, assetId: asset.id } }); await markContractFullySigned(contract.id); res.json({ signer: signed, asset }); });
export default router;
