/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5gPArmsU1KqiegWjTKUdXX
// Component: -S7sfUbedi3J

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import { AntdMenu } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5gPArmsU1KqiegWjTKUdXX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 5gPArmsU1KqiegWjTKUdXX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 5gPArmsU1KqiegWjTKUdXX/projectcss
import sty from "./PlasmicNavigation.module.css"; // plasmic-import: -S7sfUbedi3J/css

import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: 0uVdqPTYvCUB/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: _7B8Z9P_HYtH/icon

createPlasmicElementProxy;

export type PlasmicNavigation__VariantMembers = {};
export type PlasmicNavigation__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavigation__VariantsArgs;
export const PlasmicNavigation__VariantProps = new Array<VariantPropType>();

export type PlasmicNavigation__ArgsType = {};
type ArgPropType = keyof PlasmicNavigation__ArgsType;
export const PlasmicNavigation__ArgProps = new Array<ArgPropType>();

export type PlasmicNavigation__OverridesType = {
  root?: Flex__<typeof AntdMenu>;
};

export interface DefaultNavigationProps {
  className?: string;
}

const $$ = {};

function PlasmicNavigation__RenderFunc(props: {
  variants: PlasmicNavigation__VariantsArgs;
  args: PlasmicNavigation__ArgsType;
  overrides: PlasmicNavigation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const dataSourcesCtx = usePlasmicDataSourceContext();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <AntdMenu
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      expandIcon={null}
      mode={
        hasVariant(globalVariants, "screen", "mobileOnly")
          ? "horizontal"
          : "horizontal"
      }
    >
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__otwA4)}
        key={"menuItemKey0"}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__dlzcm
          )}
        >
          {"StarterKit"}
        </div>
      </AntdMenuItem>
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__lDEu)}
        key={"menuItemKey3"}
        onClick={async () => {
          const $steps = {};

          $steps["goToHomepage"] = true
            ? (() => {
                const actionArgs = {};
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    location.assign(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goToHomepage"] != null &&
            typeof $steps["goToHomepage"] === "object" &&
            typeof $steps["goToHomepage"].then === "function"
          ) {
            $steps["goToHomepage"] = await $steps["goToHomepage"];
          }
        }}
      >
        <div className={classNames(projectcss.all, sty.freeBox__sbbD8)}>
          <Icon10Icon
            className={classNames(projectcss.all, sty.svg__yaD)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lSi4M
            )}
          >
            {"Everyone"}
          </div>
        </div>
      </AntdMenuItem>
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__rkUz)}
        key={"menuItemKey4"}
        onClick={async () => {
          const $steps = {};

          $steps["goToMyProfile"] = true
            ? (() => {
                const actionArgs = {};
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    location.assign(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goToMyProfile"] != null &&
            typeof $steps["goToMyProfile"] === "object" &&
            typeof $steps["goToMyProfile"].then === "function"
          ) {
            $steps["goToMyProfile"] = await $steps["goToMyProfile"];
          }
        }}
      >
        <div className={classNames(projectcss.all, sty.freeBox__gW5DA)}>
          <Icon11Icon
            className={classNames(projectcss.all, sty.svg__uuviU)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___7WkK
            )}
          >
            {"Submit Feedback"}
          </div>
        </div>
      </AntdMenuItem>
      <div className={classNames(projectcss.all, sty.freeBox__c3L4J)}>
        {(() => {
          try {
            return !currentUser.isLoggedIn;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <AntdButton
            className={classNames("__wab_instance", sty.button__cUfnI)}
            onClick={async () => {
              const $steps = {};

              $steps["logIn"] = true
                ? (() => {
                    const actionArgs = {};
                    return (async ({ continueTo }) => {
                      function uuidv4() {
                        return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(
                          /[018]/g,
                          c =>
                            (
                              c ^
                              (crypto.getRandomValues(new Uint8Array(1))[0] &
                                (15 >> (c / 4)))
                            ).toString(16)
                        );
                      }

                      async function sha256(text) {
                        const encoder = new TextEncoder();
                        const data = encoder.encode(text);
                        const hashBuffer = await crypto.subtle.digest(
                          "SHA-256",
                          data
                        );
                        const hashArray = Array.from(
                          new Uint8Array(hashBuffer)
                        );
                        const hashHex = hashArray
                          .map(b => b.toString(16).padStart(2, "0"))
                          .join("");
                        return hashHex;
                      }

                      const state = JSON.stringify({
                        continueTo: continueTo || window.location.href
                      });
                      const code_verifier = uuidv4();
                      localStorage.setItem("code_verifier", code_verifier);
                      const code_challenge = await sha256(code_verifier);

                      const params = new URLSearchParams();
                      params.set("client_id", "5gPArmsU1KqiegWjTKUdXX");
                      params.set("state", state);
                      params.set("response_type", "code");
                      params.set("code_challenge", code_challenge);
                      params.set("code_challenge_method", "S256");
                      params.set("origin_host", window.location.host);

                      if (dataSourcesCtx?.authRedirectUri) {
                        params.set(
                          "redirect_uri",
                          dataSourcesCtx.authRedirectUri
                        );
                      }

                      if (window.__PLASMIC_AUTH_OVERRIDE) {
                        window.__PLASMIC_AUTH_OVERRIDE();
                      } else {
                        const url = `https://studio.plasmic.app/authorize?${params.toString()}`;
                        window.location.assign(url);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["logIn"] != null &&
                typeof $steps["logIn"] === "object" &&
                typeof $steps["logIn"].then === "function"
              ) {
                $steps["logIn"] = await $steps["logIn"];
              }
            }}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7GW1
              )}
            >
              {"Log in"}
            </div>
          </AntdButton>
        ) : null}
        {(() => {
          try {
            return currentUser.isLoggedIn;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <AntdButton
            className={classNames("__wab_instance", sty.button___7YfBv)}
            onClick={async () => {
              const $steps = {};

              $steps["logOut"] = true
                ? (() => {
                    const actionArgs = {};
                    return (async ({ continueTo }) => {
                      try {
                        localStorage.removeItem("plasmic_user");
                        localStorage.removeItem("$user.5gPArmsU1KqiegWjTKUdXX");
                      } catch (e) {}

                      if (window.__PLASMIC_AUTH_OVERRIDE) {
                        window.__PLASMIC_AUTH_OVERRIDE();
                      } else {
                        window.location.assign(
                          continueTo || window.location.href
                        );
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["logOut"] != null &&
                typeof $steps["logOut"] === "object" &&
                typeof $steps["logOut"].then === "function"
              ) {
                $steps["logOut"] = await $steps["logOut"];
              }
            }}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___0FasJ
              )}
            >
              {"Log out"}
            </div>
          </AntdButton>
        ) : null}
      </div>
    </AntdMenu>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof AntdMenu;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavigation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavigation__VariantsArgs;
    args?: PlasmicNavigation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavigation__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavigation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavigation__ArgProps,
          internalVariantPropNames: PlasmicNavigation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavigation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavigation";
  } else {
    func.displayName = `PlasmicNavigation.${nodeName}`;
  }
  return func;
}

export const PlasmicNavigation = Object.assign(
  // Top-level PlasmicNavigation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNavigation
    internalVariantProps: PlasmicNavigation__VariantProps,
    internalArgProps: PlasmicNavigation__ArgProps
  }
);

export default PlasmicNavigation;
/* prettier-ignore-end */
