/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5gPArmsU1KqiegWjTKUdXX

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_4G1BjwGXziv6 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 4g1bjwGXziv6/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_4G1BjwGXziv6
});
