/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5gPArmsU1KqiegWjTKUdXX
// Component: sBGlK9d2_0JZ

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import PageLayout from "../../PageLayout"; // plasmic-import: f6xT3Bj4PMCl/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { RichTable } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5gPArmsU1KqiegWjTKUdXX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 5gPArmsU1KqiegWjTKUdXX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 5gPArmsU1KqiegWjTKUdXX/projectcss
import sty from "./PlasmicSubmit.module.css"; // plasmic-import: sBGlK9d2_0JZ/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicSubmit__VariantMembers = {};
export type PlasmicSubmit__VariantsArgs = {};
type VariantPropType = keyof PlasmicSubmit__VariantsArgs;
export const PlasmicSubmit__VariantProps = new Array<VariantPropType>();

export type PlasmicSubmit__ArgsType = {};
type ArgPropType = keyof PlasmicSubmit__ArgsType;
export const PlasmicSubmit__ArgProps = new Array<ArgPropType>();

export type PlasmicSubmit__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  section?: Flex__<"section">;
  h6?: Flex__<"h6">;
  p?: Flex__<"p">;
  form3?: Flex__<typeof FormWrapper>;
  input3?: Flex__<typeof AntdInput>;
  textArea3?: Flex__<typeof AntdTextArea>;
  table2?: Flex__<typeof RichTable>;
};

export interface DefaultSubmitProps {
  className?: string;
}

const $$ = {};

function PlasmicSubmit__RenderFunc(props: {
  variants: PlasmicSubmit__VariantsArgs;
  args: PlasmicSubmit__ArgsType;
  overrides: PlasmicSubmit__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "table2.selectedRowKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKey", RichTable_Helpers)
      },
      {
        path: "table2.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRow", RichTable_Helpers)
      },
      {
        path: "table2.selectedRows",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRows", RichTable_Helpers)
      },
      {
        path: "form3.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        refName: "form3",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "input3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "textArea3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "table2.selectedRowKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKeys", RichTable_Helpers)
      },
      {
        path: "form3.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false,

        refName: "form3",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $q: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    feedback: usePlasmicDataOp(() => {
      return {
        sourceId: "6sAnWaUMPKUwEuAg6CWADc",
        opId: "3e7b4773-f808-4941-a2e6-a1b31fc10e67",
        userArgs: {},
        cacheKey: `plasmic.$.3e7b4773-f808-4941-a2e6-a1b31fc10e67.$.`,
        invalidatedKeys: null,
        roleId: "976215fd-4c84-4dfa-a06a-e81ab704b604"
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___3AaWi)}>
            <PageLayout
              data-plasmic-name={"pageLayout"}
              data-plasmic-override={overrides.pageLayout}
              className={classNames("__wab_instance", sty.pageLayout)}
            >
              <DataCtxReader__>
                {$ctx => (
                  <section
                    data-plasmic-name={"section"}
                    data-plasmic-override={overrides.section}
                    className={classNames(projectcss.all, sty.section)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__y4Wx9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lwChF
                        )}
                      >
                        <h6
                          data-plasmic-name={"h6"}
                          data-plasmic-override={overrides.h6}
                          className={classNames(
                            projectcss.all,
                            projectcss.h6,
                            projectcss.h6__5gPAr,
                            projectcss.__wab_text,
                            sty.h6
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentUser.email;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Anonymous";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </h6>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.h4__5gPAr,
                            projectcss.__wab_text,
                            sty.h4___4HPFj
                          )}
                        >
                          {"Submit Feedback"}
                        </h4>
                        <p
                          data-plasmic-name={"p"}
                          data-plasmic-override={overrides.p}
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.p__5gPAr,
                            projectcss.__wab_text,
                            sty.p
                          )}
                        >
                          {"Share your thoughts, issues and suggestions."}
                        </p>
                      </div>
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.form3),
                          extendedOnValuesChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["form3", "value"],
                              FormWrapper_Helpers
                            ).apply(null, eventArgs);
                          },
                          formItems: [
                            { label: "Name", name: "name", inputType: "Text" },
                            {
                              label: "Message",
                              name: "message",
                              inputType: "Text Area"
                            }
                          ],
                          labelCol: { span: 8, horizontalOnly: true },
                          layout: "vertical",
                          mode: undefined,
                          onFinish: async values => {
                            const $steps = {};

                            $steps["postgresCreate"] = true
                              ? (() => {
                                  const actionArgs = {
                                    dataOp: {
                                      sourceId: "6sAnWaUMPKUwEuAg6CWADc",
                                      opId: "fba13a4c-a688-44aa-9d80-be8cee136833",
                                      userArgs: {
                                        variables: [
                                          $state.form3.value.feedback,

                                          $state.form3.value.title
                                        ]
                                      },
                                      cacheKey: null,
                                      invalidatedKeys: ["plasmic_refresh_all"],
                                      roleId: null
                                    }
                                  };
                                  return (async ({
                                    dataOp,
                                    continueOnError
                                  }) => {
                                    try {
                                      const response =
                                        await executePlasmicDataOp(dataOp, {
                                          userAuthToken:
                                            dataSourcesCtx?.userAuthToken,
                                          user: dataSourcesCtx?.user
                                        });
                                      await plasmicInvalidate(
                                        dataOp.invalidatedKeys
                                      );
                                      return response;
                                    } catch (e) {
                                      if (!continueOnError) {
                                        throw e;
                                      }
                                      return e;
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["postgresCreate"] != null &&
                              typeof $steps["postgresCreate"] === "object" &&
                              typeof $steps["postgresCreate"].then ===
                                "function"
                            ) {
                              $steps["postgresCreate"] =
                                await $steps["postgresCreate"];
                            }

                            $steps["goToSubmit"] = true
                              ? (() => {
                                  const actionArgs = { destination: `/submit` };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      location.assign(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["goToSubmit"] != null &&
                              typeof $steps["goToSubmit"] === "object" &&
                              typeof $steps["goToSubmit"].then === "function"
                            ) {
                              $steps["goToSubmit"] = await $steps["goToSubmit"];
                            }
                          },
                          onIsSubmittingChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "isSubmitting",
                              ["form3", "isSubmitting"],
                              FormWrapper_Helpers
                            ).apply(null, eventArgs);
                          },
                          ref: ref => {
                            $refs["form3"] = ref;
                          },
                          submitSlot: (
                            <AntdButton
                              className={classNames(
                                "__wab_instance",
                                sty.button__vGxbs
                              )}
                              submitsForm={true}
                              type={"primary"}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__cRia
                                )}
                              >
                                {"Submit"}
                              </div>
                            </AntdButton>
                          ),
                          wrapperCol: { span: 16, horizontalOnly: true }
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "form3.value"
                            },
                            {
                              name: "isSubmitting",
                              plasmicStateName: "form3.isSubmitting"
                            }
                          ],
                          [],
                          FormWrapper_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <FormWrapper
                            data-plasmic-name={"form3"}
                            data-plasmic-override={overrides.form3}
                            {...child$Props}
                          >
                            <FormItemWrapper
                              className={classNames(
                                "__wab_instance",
                                sty.formField___3BZw5
                              )}
                              label={
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__pfiT6
                                  )}
                                >
                                  {"Title"}
                                </div>
                              }
                              name={"title"}
                            >
                              {(() => {
                                const child$Props = {
                                  className: classNames(
                                    "__wab_instance",
                                    sty.input3
                                  ),
                                  onChange: async (...eventArgs: any) => {
                                    generateStateOnChangePropForCodeComponents(
                                      $state,
                                      "value",
                                      ["input3", "value"],
                                      AntdInput_Helpers
                                    ).apply(null, eventArgs);
                                  },
                                  value: generateStateValueProp($state, [
                                    "input3",
                                    "value"
                                  ])
                                };
                                initializeCodeComponentStates(
                                  $state,
                                  [
                                    {
                                      name: "value",
                                      plasmicStateName: "input3.value"
                                    }
                                  ],
                                  [],
                                  AntdInput_Helpers ?? {},
                                  child$Props
                                );

                                return (
                                  <AntdInput
                                    data-plasmic-name={"input3"}
                                    data-plasmic-override={overrides.input3}
                                    {...child$Props}
                                  />
                                );
                              })()}
                            </FormItemWrapper>
                            <FormItemWrapper
                              className={classNames(
                                "__wab_instance",
                                sty.formField__i8H7P
                              )}
                              label={
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__w47ER
                                  )}
                                >
                                  {"Feedback"}
                                </div>
                              }
                              name={"feedback"}
                            >
                              {(() => {
                                const child$Props = {
                                  className: classNames(
                                    "__wab_instance",
                                    sty.textArea3
                                  ),
                                  onChange: async (...eventArgs: any) => {
                                    generateStateOnChangePropForCodeComponents(
                                      $state,
                                      "value",
                                      ["textArea3", "value"],
                                      AntdTextArea_Helpers
                                    ).apply(null, eventArgs);
                                  },
                                  value: generateStateValueProp($state, [
                                    "textArea3",
                                    "value"
                                  ])
                                };
                                initializeCodeComponentStates(
                                  $state,
                                  [
                                    {
                                      name: "value",
                                      plasmicStateName: "textArea3.value"
                                    }
                                  ],
                                  [],
                                  AntdTextArea_Helpers ?? {},
                                  child$Props
                                );

                                return (
                                  <AntdTextArea
                                    data-plasmic-name={"textArea3"}
                                    data-plasmic-override={overrides.textArea3}
                                    {...child$Props}
                                  />
                                );
                              })()}
                            </FormItemWrapper>
                            <AntdButton
                              className={classNames(
                                "__wab_instance",
                                sty.button__eUnaj
                              )}
                              size={"large"}
                              submitsForm={true}
                              type={"primary"}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__pQ8A0
                                )}
                              >
                                {"Submit"}
                              </div>
                            </AntdButton>
                          </FormWrapper>
                        );
                      })()}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cvDCf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__barbw
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.h4__5gPAr,
                            projectcss.__wab_text,
                            sty.h4__qf880
                          )}
                        >
                          {"My Feedback"}
                        </h4>
                      </div>
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.table2),
                          data: (() => {
                            try {
                              return $queries.feedback;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          defaultSize: hasVariant(
                            globalVariants,
                            "screen",
                            "mobileOnly"
                          )
                            ? "small"
                            : undefined,
                          fields: (() => {
                            const __composite = [
                              { key: "id", fieldId: "id", isHidden: null },
                              {
                                key: "author_id",
                                fieldId: "author_id",
                                isHidden: null
                              },
                              { key: "title", fieldId: "title" },
                              { key: "feedback", fieldId: "feedback" },
                              { key: "status", fieldId: "status" },
                              { key: "response", fieldId: "response" },
                              { key: "created_at", fieldId: "created_at" }
                            ];
                            __composite["0"]["isHidden"] = true;
                            __composite["1"]["isHidden"] = true;
                            return __composite;
                          })(),

                          onRowSelectionChanged: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRowKey",
                              ["table2", "selectedRowKey"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRow",
                              ["table2", "selectedRow"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRows",
                              ["table2", "selectedRows"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRowKeys",
                              ["table2", "selectedRowKeys"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                          },
                          pageSize: 10,
                          scopeClassName: sty["table2__instance"],
                          selectedRowKey: generateStateValueProp($state, [
                            "table2",
                            "selectedRowKey"
                          ]),
                          selectedRowKeys: generateStateValueProp($state, [
                            "table2",
                            "selectedRowKeys"
                          ]),
                          themeResetClassName: classNames(
                            projectcss.root_reset,
                            projectcss.root_reset_tags,
                            projectcss.plasmic_default_styles,
                            projectcss.plasmic_mixins,
                            styleTokensClassNames
                          )
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "selectedRowKey",
                              plasmicStateName: "table2.selectedRowKey"
                            },
                            {
                              name: "selectedRow",
                              plasmicStateName: "table2.selectedRow"
                            },
                            {
                              name: "selectedRows",
                              plasmicStateName: "table2.selectedRows"
                            },
                            {
                              name: "selectedRowKeys",
                              plasmicStateName: "table2.selectedRowKeys"
                            }
                          ],
                          [],
                          RichTable_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <RichTable
                            data-plasmic-name={"table2"}
                            data-plasmic-override={overrides.table2}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  </section>
                )}
              </DataCtxReader__>
            </PageLayout>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageLayout",
    "section",
    "h6",
    "p",
    "form3",
    "input3",
    "textArea3",
    "table2"
  ],
  pageLayout: [
    "pageLayout",
    "section",
    "h6",
    "p",
    "form3",
    "input3",
    "textArea3",
    "table2"
  ],
  section: ["section", "h6", "p", "form3", "input3", "textArea3", "table2"],
  h6: ["h6"],
  p: ["p"],
  form3: ["form3", "input3", "textArea3"],
  input3: ["input3"],
  textArea3: ["textArea3"],
  table2: ["table2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  section: "section";
  h6: "h6";
  p: "p";
  form3: typeof FormWrapper;
  input3: typeof AntdInput;
  textArea3: typeof AntdTextArea;
  table2: typeof RichTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSubmit__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSubmit__VariantsArgs;
    args?: PlasmicSubmit__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSubmit__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSubmit__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSubmit__ArgProps,
          internalVariantPropNames: PlasmicSubmit__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSubmit__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSubmit";
  } else {
    func.displayName = `PlasmicSubmit.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={"976215fd-4c84-4dfa-a06a-e81ab704b604"}
      appId={"5gPArmsU1KqiegWjTKUdXX"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "5gPArmsU1KqiegWjTKUdXX"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicSubmit = Object.assign(
  // Top-level PlasmicSubmit renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    section: makeNodeComponent("section"),
    h6: makeNodeComponent("h6"),
    p: makeNodeComponent("p"),
    form3: makeNodeComponent("form3"),
    input3: makeNodeComponent("input3"),
    textArea3: makeNodeComponent("textArea3"),
    table2: makeNodeComponent("table2"),

    // Metadata about props expected for PlasmicSubmit
    internalVariantProps: PlasmicSubmit__VariantProps,
    internalArgProps: PlasmicSubmit__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/submit",
      pagePath: "/submit",
      params: {},
      query: {}
    })
  }
);

export default PlasmicSubmit;
/* prettier-ignore-end */
